version: '3.9'

services:
    book_store:
      build: ./
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - book_db
    book_db:
      image: 'postgres:latest'
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env  
      volumes:
      - ./db-data/:/var/lib/postgresql/data/
      
volumes:
  db:
    driver: local
    
# THIS IS A COPY OF MY .env FILE
# # Postgres DB env variables
# DB_ADDRESS=book_db
# DB_PORT=5432

# POSTGRES_USER=postgres
# POSTGRES_PASSWORD=I240959ko
# POSTGRES_DB=books_store

# # JWT env variablies
# ACCESS_SECRET=jdnfksdmfksd
# REFRESH_SECRET=mcmvmkmsdnfsdmfdsjf