version: '3.9'

services:
    book_store:
      build: ./
      #---------------------------------------------------------------------------
      ports:
        - 8080:8080
      depends_on:
        - db
    db:
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: 'postgres'
      volumes:
        - database_data:/var/lib/postgresql/data
        - ./internal/repositoryDB/postgresDB/instructions.sql:/docker-entrypoint-initdb.d/instructions.sql

volumes:
  database_data:
    driver: local