version: '3.9'

services:
    book_store:
      build: ./
      ports:
        - 8080:8080
      depends_on:
        - db
    db:
      image: 'postgres:latest'
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env  
      volumes:
      - ./db-data/:/var/lib/postgresql/data/
      
volumes:
  db:
    driver: local